// import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '@/theme';
import { ReactNode } from 'react';
import "./globals.css";
import Head from 'next/head';
import type { Metadata } from "next";
import localFont from "next/font/local";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"></meta>
        <meta charSet="utf-8"></meta>
        <meta name="description" content="東京都市大学 理工学部 機械システム工学科 高機能機械制御研究室HP"></meta>
        <meta name="keywords" content="東京都市大学,機械システム工学科,機械,制御,電機" />
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
        <title>
          Advanced Control Systems Lab in TCU
        </title>
        <link rel="shortcut icon" href="/logo.ico" />
      </Head>

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider theme={theme}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
// <AppRouterCacheProvider>
//   <ThemeProvider theme={theme}>
//     <CssBaseline />
//     {children}
//   </ThemeProvider>
// </AppRouterCacheProvider>